### PR TITLE
Components/formatted text

### PR DESCRIPTION
**Pull request by swarup4741**
Replaced the `className="formatted"` lines with `FormattedText` component in `/client/curriculum/css/*`

Is this ok? if it is then i will proceed with the rest of the files and finally push them in a single commit

### CODE REVIEW

**Comment by iampava** [comment]
Yes, this is perfect <3 You can proceed with the rest of the files 🙏

**Review by iampava — COMMENTED** [review]
Just had a look through all the files, looks great 💪

There's only 1 line left to change in `Lists.tsx`:

```
<strong className="formatted">a</strong>
```

Let's also delete the old `.formatted` styles in `_lessons.scss`.

Then squash all commits and I'll merge them :D

**Review by swarup4741 — COMMENTED** [review]
Changed to FormattedText component in `Lists.tsx`  and removed `_lessons.scss`... hope now everything is well and good

**Comment by iampava** [comment]
> 
> 
> Changed to FormattedText component in `Lists.tsx` and removed `_lessons.scss`... hope now everything is well and good

It's great. Just squash the commits I'll merge :D

**Review by swarup4741 — COMMENTED** [review]
Squashed all the commits into one `[REFACTOR] Separated Formatted text into a component (#232)`

**Review by iampava — APPROVED** [review]

**Comment by iampava** [comment]
Perfect. Thank you very much. Merged this PR 🥳

I also added you to the Contributors section in README.md: https://github.com/FrontEnd-ro/frontend.ro/blob/master/README.md

image

**Comment by swarup4741** [comment]
@iampava  Thank you for teaching me so much and guiding me all the way through. This couldn't have been possible without your help ❤️

**Pull request merged**
