### PR TITLE
Grammatical error.

### PR DESCRIPTION
**Pull request by lazarnarcis**
Only one extra letter was added to the word "le".

### CODE REVIEW

**Comment by iampava** [comment]
Thanks for spotting this error. Please create an issue, then rename the commit according to the guidelines inside CHANGELOG.md

**Comment by lazarnarcis** [comment]
It's ok?

**Comment by iampava** [comment]
It's almost ok. It should have the link to the Issue, not the PR.

Also, please modify the issue name to include the page where the grammatical error is.

**Comment by lazarnarcis** [comment]
It's ok? :)

**Comment by iampava** [comment]
You have 2 commits, should be just one

**Pull request closed without merging**
